name: Compile
on: [push, pull_request]
jobs:  
  matrix-compile:
    env:      
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      ARDUINO_LIBRARY_ENABLE_UNSAFE_INSTALL: true
      ARDUINO_BOARD_MANAGER_ADDITIONAL_URLS: http://arduino.esp8266.com/stable/package_esp8266com_index.json
    
    strategy:
      matrix:
        # The matrix will produce one job for each configuration
        # parameter of type arduino-platform, in this case a
        # total of 2.
        arduino-platform: ["esp8266:esp8266"]
        include:
          - arduino-platform: "esp8266:esp8266"
            fqbn: "esp8266:esp8266:nodemcuv2"

    runs-on: windows-latest 
    
    steps:
      # First of all, we clone the repo using the checkout action.
      - name: Checkout
        uses: actions/checkout@master
 
      # We use the arduino/setup-arduino-cli action to install and
      # configure the Arduino CLI on the system.
      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1.0.0
 
      # We then install the platform, which one will be determined
      # dynamically by the build matrix.
      - name: Install platform
        run: |
          arduino-cli config init
          arduino-cli core update-index --additional-urls http://arduino.esp8266.com/stable/package_esp8266com_index.json
          arduino-cli config dump --verbose
          arduino-cli core install ${{ matrix.arduino-platform }}

      # We install the required libraries.
      - name: Install libraries
        run: |
          arduino-cli lib install "ArduinoJson"
          arduino-cli lib install "WebSockets"
          arduino-cli lib install "ArduinoWebsockets"
          arduino-cli lib install --git-url https://github.com/morrissinger/ESP8266-Websocket
 
      # Finally, we compile the sketch, using the FQBN that was set
      # in the build matrix.
      - name: Compile Sketch
        run: arduino-cli compile --fqbn ${{ matrix.fqbn }}
