name: T

on:
  push:
  #workflow_dispatch:

jobs: 
  test:
    strategy:
      fail-fast: false
      matrix:
         board: 
           - fqbn: arduino:avr:uno 
             platforms: | 
               - name: arduino:avr 
                 version: 1.8.3 
             libraries: | 
               - name: Servo 
                 version: 1.1.7 
           # Board that requires Boards Manager URL 
           - fqbn: esp8266:esp8266:huzzah 
             platforms: | 
               - name: esp8266:esp8266 
                 source-url: https://arduino.esp8266.com/stable/package_esp8266com_index.json 
                 version: 2.7.4 
             libraries: | 
               # The official Servo library is not compatible with ESP8266, but that platform has a bundled Servo lib 
               # so there are no library dependencies 
               -
   
    runs-on: windows-latest
 
    steps: 
      - name: Checkout 
        uses: actions/checkout@v3

      - name: Setup Arduino CLI 
        uses: arduino/setup-arduino-cli@v1
 
      - name: Install platform 
        run: | 
          arduino-cli core update-index 
          arduino-cli core install ${{ matrix.arduino-platform }} 

      - name: Compile Sketch 
        run: arduino-cli compile --fqbn ${{ matrix.fqbn }} ./Main
