name: PlatformIO CI
on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      # First of all, we clone the repo using the checkout action.
      - name: Checkout
        uses: actions/checkout@master
        
      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
          
      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio
        
      # It is important to first install the libraries before compiling, since otherwise compilation might fail to find the just-installed libraries
      - name: Install platformIO libraries
        run: pio lib install
      - name: Run PlatformIO
        run: platformio run
